/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

val hk2Version = "2.5.0-b61"
plugins {
    java
}

repositories {
    mavenCentral()
//    maven("https://jitpack.io")
}

dependencies {
    implementation("io.dropwizard:dropwizard-bom:1.3.3")
    compile("io.dropwizard:dropwizard-core")
    compile("org.glassfish.hk2:hk2-api:$hk2Version")
    compile("org.glassfish.hk2:hk2-locator:$hk2Version")
    compile("org.glassfish.hk2:hk2-extras:$hk2Version")
}
